#define AUTO_SHIFT_MODIFIERS
#define NO_AUTO_SHIFT_ALPHA

#define COMBO_STRICT_TIMER

#define RGB_MATRIX_SLEEP
#define RGB_MATRIX_DEFAULT_ON false
// #define ENABLE_RGB_MATRIX_HUE_WAVE

// #define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

// #define HOLD_ON_OTHER_KEY_PRESS
#define PERMISSIVE_HOLD
#define TAPPING_TERM 220
#define QUICK_TAP_TERM_PER_KEY
// #define QUICK_TAP_TERM 0

#define DUMMY_MOD_NEUTRALIZER_KEYCODE KC_RIGHT_CTRL
#define RETRO_TAPPING

// #define DYNAMIC_TAPPING_TERM_ENABLE

