BOARD = GENERIC_RP_RP2040
COMBO_ENABLE = yes
# AUTO_SHIFT_ENABLE = yes
# TAP_DANCE_ENABLE = yes
# RGB_MATRIX_DRIVER = ws2812
TRI_LAYER_ENABLE = yes
CAPS_WORD_ENABLE = yes
CONSOLE_ENABLE = yes

# SRC += features/achordion.c
 
