#define ENCODER_MAP_KEY_DELAY 10

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define HOLD_ON_OTHER_KEY_PRESS
// #define PERMISSIVE_HOLD
#define CHORDAL_HOLD
#define TAPPING_TERM 200

// #define QUICK_TAP_TERM_PER_KEY
// #define QUICK_TAP_TERM 0

// #define RETRO_TAPPING

// #define DYNAMIC_TAPPING_TERM_ENABLE

#define COMBO_TERM 50
// #define COMBO_STRICT_TIMER


#define MK_KINETIC_SPEED 10
#define MOUSEKEY_DELAY 10

